version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    ports:
      - '5454:5432'
    environment:
      - POSTGRES_DB=db_chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - db_chat_volume:/var/lib/postgresql/data/